#!/usr/bin/env python3

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd
import torch
import torch.nn.functional as F
from datasets import Dataset
from peft import LoraConfig, TaskType, get_peft_model
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    EarlyStoppingCallback,
    HfArgumentParser,
    Trainer,
    TrainingArguments,
)

from grc_pipeline_utils import get_grc_special_tokens, get_sid_special_tokens


@dataclass
class ModelArguments:
    model_name_or_path: Optional[str] = field(
        default="../basemodel/Qwen3-1-7B-expand",
        metadata={"help": "Warm-up / backbone model path."},
    )
    use_lora: bool = field(default=True, metadata={"help": "Whether to use LoRA."})
    lora_r: int = field(default=64, metadata={"help": "LoRA rank."})
    lora_alpha: int = field(default=64, metadata={"help": "LoRA alpha."})
    lora_dropout: float = field(default=0.05, metadata={"help": "LoRA dropout."})
    lora_target_modules: str = field(
        default="q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj",
        metadata={"help": "Comma-separated LoRA target modules."},
    )


@dataclass
class DataArguments:
    train_data_path: str = field(
        default="./train/grc_sft_train.parquet",
        metadata={"help": "Candidate-level GRC SFT parquet generated by build_grc_sft_dataset.py."},
    )
    val_data_path: Optional[str] = field(
        default=None,
        metadata={"help": "Optional validation parquet path."},
    )
    validation_split_ratio: float = field(
        default=0.05,
        metadata={"help": "Validation split when val_data_path is omitted."},
    )
    text_column: str = field(
        default="text",
        metadata={"help": "Column that stores the final SFT training text."},
    )
    max_train_samples: Optional[int] = field(default=None)
    max_val_samples: Optional[int] = field(default=None)


@dataclass
class GRCArguments:
    max_length: int = field(default=4096)
    rc_loss_weight: float = field(
        default=1.2,
        metadata={"help": "Lambda_rc in the paper."},
    )
    num_levels: int = field(default=4)
    codebook_size: int = field(default=256)


def is_main_process(local_rank: int) -> bool:
    return local_rank in (-1, 0)


def maybe_limit(dataframe: pd.DataFrame, max_rows: Optional[int]) -> pd.DataFrame:
    if max_rows is None or len(dataframe) <= max_rows:
        return dataframe
    return dataframe.iloc[:max_rows].reset_index(drop=True)


def split_train_val(dataframe: pd.DataFrame, ratio: float, seed: int):
    if not 0.0 < ratio < 1.0:
        raise ValueError("validation_split_ratio must be in (0, 1).")
    shuffled = dataframe.sample(frac=1.0, random_state=seed).reset_index(drop=True)
    val_size = max(1, int(len(shuffled) * ratio))
    val_dataframe = shuffled.iloc[:val_size].reset_index(drop=True)
    train_dataframe = shuffled.iloc[val_size:].reset_index(drop=True)
    return train_dataframe, val_dataframe


def format_preview_value(value: Any) -> str:
    if value is None:
        return ""
    return str(value)


def print_dataframe_preview(name: str, dataframe: pd.DataFrame, limit: int = 3):
    print(f"\n===== {name} Preview ({min(len(dataframe), limit)}/{len(dataframe)}) =====")
    if len(dataframe) == 0:
        print("No rows available.")
        return

    preview_rows = dataframe.head(limit).to_dict("records")
    for index, row in enumerate(preview_rows, start=1):
        print(f"[{name} #{index}]")
        if "user_id" in row:
            print(f"user_id: {row.get('user_id', '')}")
        if "input" in row:
            print("input:")
            print(format_preview_value(row.get("input", "")))
        if "target_sid" in row:
            print(f"target_sid: {row.get('target_sid', '')}")
        if "draft_sid" in row:
            print(f"draft_sid: {row.get('draft_sid', '')}")
        if "reflection_sequence" in row:
            print(f"reflection_sequence: {row.get('reflection_sequence', '')}")
        if "loc_label_token" in row:
            print(f"loc_label_token: {row.get('loc_label_token', '')}")
        if "leaf_label_token" in row:
            print(
                "leaf_label_token: "
                f"{row.get('leaf_label_token', '')} "
                f"(score={row.get('leaf_severity_score', '')}, bucket={row.get('leaf_severity_bucket', '')})"
            )
        if "brand_label_token" in row:
            print(
                "brand_label_token: "
                f"{row.get('brand_label_token', '')} "
                f"(score={row.get('brand_severity_score', '')}, bucket={row.get('brand_severity_bucket', '')})"
            )
        if "text" in row:
            print("text:")
            print(format_preview_value(row.get("text", "")))
        print("-" * 80)


def tokenize_function(examples, tokenizer, text_column: str, max_length: int):
    return tokenizer(
        examples[text_column],
        padding="longest",
        truncation=True,
        max_length=max_length,
        add_special_tokens=True,
        return_attention_mask=True,
    )


def dataframe_to_dataset(dataframe: pd.DataFrame, text_column: str) -> Dataset:
    if text_column not in dataframe.columns:
        raise ValueError(f"Column '{text_column}' not found. Available columns: {list(dataframe.columns)}")
    return Dataset.from_pandas(dataframe[[text_column]], preserve_index=False)


class GRCDataCollator:
    def __init__(self, tokenizer):
        self.tokenizer = tokenizer
        self.assistant_prefix_tokens = tokenizer.encode(
            "<|im_start|>assistant\n",
            add_special_tokens=False,
        )
        self.reflect_token_id = tokenizer.convert_tokens_to_ids("<|grc_reflect|>")

    @staticmethod
    def _find_subsequence(sequence: List[int], pattern: List[int]) -> int:
        if not pattern or len(sequence) < len(pattern):
            return -1
        for start in range(len(sequence) - len(pattern) + 1):
            if sequence[start : start + len(pattern)] == pattern:
                return start
        return -1

    def __call__(self, features: List[Dict[str, Any]]) -> Dict[str, Any]:
        input_ids = [feature["input_ids"] for feature in features]
        attention_mask = [feature["attention_mask"] for feature in features]

        max_length = max(len(ids) for ids in input_ids)
        padded_input_ids = []
        padded_attention_mask = []
        labels = []
        loss_group = []

        for ids, mask in zip(input_ids, attention_mask):
            padding_length = max_length - len(ids)
            padded_ids = ids + [self.tokenizer.pad_token_id] * padding_length
            padded_mask = mask + [0] * padding_length

            label = padded_ids.copy()
            group = [0] * len(padded_ids)

            assistant_start = self._find_subsequence(ids, self.assistant_prefix_tokens)
            if assistant_start != -1:
                assistant_start += len(self.assistant_prefix_tokens)

            if assistant_start == -1:
                label = [-100] * len(label)
                group = [-100] * len(group)
            else:
                reflect_start = -1
                for index in range(assistant_start, len(ids)):
                    if ids[index] == self.reflect_token_id:
                        reflect_start = index
                        break
                if reflect_start == -1:
                    reflect_start = len(ids)

                for index in range(assistant_start):
                    label[index] = -100
                    group[index] = -100
                for index in range(assistant_start, min(reflect_start, len(ids))):
                    group[index] = 0
                for index in range(reflect_start, len(ids)):
                    group[index] = 1

            for index, attn in enumerate(padded_mask):
                if attn == 0:
                    label[index] = -100
                    group[index] = -100

            padded_input_ids.append(padded_ids)
            padded_attention_mask.append(padded_mask)
            labels.append(label)
            loss_group.append(group)

        return {
            "input_ids": torch.tensor(padded_input_ids, dtype=torch.long),
            "attention_mask": torch.tensor(padded_attention_mask, dtype=torch.long),
            "labels": torch.tensor(labels, dtype=torch.long),
            "loss_group": torch.tensor(loss_group, dtype=torch.long),
        }


class GRCTrainer(Trainer):
    def __init__(self, *args, rc_loss_weight: float = 1.2, **kwargs):
        super().__init__(*args, **kwargs)
        self.rc_loss_weight = rc_loss_weight

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        labels = inputs.pop("labels")
        loss_group = inputs.pop("loss_group")

        outputs = model(**inputs)
        logits = outputs.logits

        shift_logits = logits[..., :-1, :].contiguous()
        shift_labels = labels[..., 1:].contiguous()
        shift_group = loss_group[..., 1:].contiguous()

        vocab_size = shift_logits.size(-1)
        token_losses = F.cross_entropy(
            shift_logits.view(-1, vocab_size),
            shift_labels.view(-1),
            reduction="none",
            ignore_index=-100,
        ).view_as(shift_labels)

        valid_mask = shift_labels.ne(-100)
        draft_mask = valid_mask & shift_group.eq(0)
        rc_mask = valid_mask & shift_group.eq(1)

        zero = shift_logits.new_zeros(())
        draft_loss = token_losses.masked_select(draft_mask).mean() if draft_mask.any() else zero
        rc_loss = token_losses.masked_select(rc_mask).mean() if rc_mask.any() else zero
        total_loss = draft_loss + self.rc_loss_weight * rc_loss

        if return_outputs:
            outputs.loss = total_loss
            return total_loss, outputs
        return total_loss


def add_special_tokens(tokenizer, model, grc_args: GRCArguments):
    tokens = get_grc_special_tokens(num_levels=grc_args.num_levels)
    added = tokenizer.add_special_tokens(
        {"additional_special_tokens": tokens},
        replace_additional_special_tokens=False,
    )
    if added > 0:
        model.resize_token_embeddings(len(tokenizer))
    return added


def build_trainable_token_ids(tokenizer, grc_args: GRCArguments):
    tokens = get_sid_special_tokens(
        num_levels=grc_args.num_levels,
        codebook_size=grc_args.codebook_size,
    ) + get_grc_special_tokens(num_levels=grc_args.num_levels)
    token_ids = tokenizer.convert_tokens_to_ids(tokens)
    valid_ids = [token_id for token_id in token_ids if token_id != tokenizer.unk_token_id]
    return sorted(set(valid_ids))


def main():
    parser = HfArgumentParser((ModelArguments, DataArguments, GRCArguments, TrainingArguments))
    model_args, data_args, grc_args, training_args = parser.parse_args_into_dataclasses()
    training_args.label_names = ["labels", "loss_group"]

    model_path = Path(model_args.model_name_or_path).resolve()
    train_data_path = Path(data_args.train_data_path).resolve()
    val_data_path = Path(data_args.val_data_path).resolve() if data_args.val_data_path else None

    if not model_path.exists():
        raise FileNotFoundError(f"Model path not found: {model_path}")
    if not train_data_path.exists():
        raise FileNotFoundError(f"Training data path not found: {train_data_path}")
    if val_data_path is not None and not val_data_path.exists():
        raise FileNotFoundError(f"Validation data path not found: {val_data_path}")

    train_dataframe = pd.read_parquet(train_data_path)
    train_dataframe = maybe_limit(train_dataframe, data_args.max_train_samples)

    if val_data_path is not None:
        val_dataframe = pd.read_parquet(val_data_path)
    else:
        train_dataframe, val_dataframe = split_train_val(
            dataframe=train_dataframe,
            ratio=data_args.validation_split_ratio,
            seed=training_args.seed,
        )
    val_dataframe = maybe_limit(val_dataframe, data_args.max_val_samples)

    if is_main_process(training_args.local_rank):
        print(f"Loaded train rows: {len(train_dataframe)}")
        print(f"Loaded val rows: {len(val_dataframe)}")
        if "reflection_combo" in train_dataframe.columns:
            print("Top reflection combos in train:")
            print(train_dataframe["reflection_combo"].value_counts().head(10).to_dict())
        print_dataframe_preview("Train", train_dataframe)
        print_dataframe_preview("Val", val_dataframe)

    model = AutoModelForCausalLM.from_pretrained(str(model_path))
    tokenizer = AutoTokenizer.from_pretrained(str(model_path))
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    added = add_special_tokens(tokenizer, model, grc_args)
    if is_main_process(training_args.local_rank):
        print(f"Added GRC tokens: {added}")

    if training_args.gradient_checkpointing:
        model.config.use_cache = False

    train_dataset = dataframe_to_dataset(train_dataframe, data_args.text_column)
    val_dataset = dataframe_to_dataset(val_dataframe, data_args.text_column)

    train_dataset = train_dataset.map(
        lambda x: tokenize_function(x, tokenizer, data_args.text_column, grc_args.max_length),
        batched=True,
        remove_columns=train_dataset.column_names,
        desc="Tokenizing GRC train data",
    )
    val_dataset = val_dataset.map(
        lambda x: tokenize_function(x, tokenizer, data_args.text_column, grc_args.max_length),
        batched=True,
        remove_columns=val_dataset.column_names,
        desc="Tokenizing GRC val data",
    )

    if model_args.use_lora:
        trainable_token_ids = build_trainable_token_ids(tokenizer, grc_args)
        lora_config = LoraConfig(
            r=model_args.lora_r,
            lora_alpha=model_args.lora_alpha,
            lora_dropout=model_args.lora_dropout,
            target_modules=model_args.lora_target_modules.split(","),
            bias="none",
            task_type=TaskType.CAUSAL_LM,
            trainable_token_indices={"embed_tokens": trainable_token_ids},
        )
        model = get_peft_model(model, lora_config)
        model.print_trainable_parameters()

    trainer = GRCTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        data_collator=GRCDataCollator(tokenizer),
        callbacks=[EarlyStoppingCallback(early_stopping_patience=5)],
        rc_loss_weight=grc_args.rc_loss_weight,
    )

    if is_main_process(training_args.local_rank):
        print("Starting GRC SFT training...")

    trainer.train()
    result = trainer.evaluate()

    if is_main_process(training_args.local_rank):
        print("Final evaluation result:")
        print(result)

    trainer.save_model(training_args.output_dir)
    tokenizer.save_pretrained(training_args.output_dir)

    if is_main_process(training_args.local_rank):
        print(f"Saved model to {training_args.output_dir}")


if __name__ == "__main__":
    main()
